[package]
name = "text-editor"
authors = ["Harsh Shandilya <me@msfjarvis.dev>"]
version = "0.1.0"
edition = "2021"
license = "MIT/Apache-2.0"

[dependencies]
anyhow = "1.0.66"
termion = "1.5.6"
unicode-segmentation = "1.10.0"
